name: Run Tests
on:
  push:
    branches: [main]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        run: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.9

      - name: install requirements
        run: |
          python.exe -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Validate your code
        run: pylint .

      - name: run unit tests
        run: pytest
